name: Deployment

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: solvedac/unofficial-documentation
          path: unofficial-documentation
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - uses: actions/setup-node@v2
      - name: Install Dependencies
        run: npm install
      - name: Override OpenAPI Version to 3.0.x (generator doe snot support 3.1)
        run: |
          for file in `find unofficial-documentation/src -type f`; do
            sed -i 's/openapi: "3.1.0"/openapi: "3.0.0"/' $file
          done
      - name: Generate
        run: npm run generate
      - name: Tricky TSC Safety
        run: |
          sed -i 's/fetchApi(): FetchAPI/fetchApi(): FetchAPI | undefined/' src/runtime.ts
      - name: Tricky TSC ESM
        run: |
          for file in `find src -type f`; do
            sed -ri "s/from '([^']+)'/from '\1.js'/" $file
          done
      - name: Build
        run: npm run build
      - name: Update Version
        run: |
          sed -ri "s/\"version\": \"[^\"]+\"/\"version\": \"`sed -rn 's/^.*  version: "([^"]+)".*$/\1/p' unofficial-documentation/src/openapi.yaml`\"/" package.json
      - name: Make Deno Friendly
        run: |
          for file in `find src -type f -name "index.ts"`; do
            cp $file `echo $file | sed s/index/mod/`
          done
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Follow-up solvedac/unofficial-documentation
          title: Follow-up solvedac/unofficial-documentation
          body: |
            This Pull Request will update the typescript sources.
            It is automatically created by GitHub Actions.
          labels: follow-up
