name: Deployment

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: solvedac/unofficial-documentation
          path: unofficial-documentation
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - uses: actions/setup-node@v2
      - name: Install OpenAPI Generator CLI
        run: npm install @openapitools/openapi-generator-cli -g
      - name: Treat OpenAPI Version as 3.0.x (Because of no support)
        run: |
          for file in `find unofficial-documentation/src -type f`; do
            sed -i 's/openapi: "3.1.0"/openapi: "3.0.0"/' $file
          done
      - name: Generate
        run: npx @openapitools/openapi-generator-cli batch typescript-fetch.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Migrate OpenAPI spec from solvedac/unofficial-documentation
          title: Migrate OpenAPI Specification from solvedac/unofficial-documentation
          body: |
            This Pull Request will update the typescript sources.
            It is automatically created by GitHub Actions.
          labels: automated
